---
- name: Install and start Apache
  hosts: all
  become: yes

  tasks:
    - name: Install httpd
      package:
        name: httpd
        state: present

    - name: Start service
      service:
        name: httpd
        state: started
        enabled: yes
